### ISSUE TITLE
Jest 27 support

### ISSUE THREAD

**Issue by flunderpero** [playwright-community/jest-playwright#665]
**Describe the bug**
I am trying to use jest-playwright with Jest 27 and get this error:
```
TypeError: virtualMocks.get is not a function

      at Resolver._getVirtualMockPath (../../node_modules/jest-resolve/build/index.js:447:25)
```

**To Reproduce**
I am using a standard installation and a single simple test that just opens a browser.

**Desktop (please complete the following information):**
 - OS: [macOS M1]
 - Playwright version [1.10.0]
 - jest-playwright version [1.5.1]
 - jest version [27.0.0-next.7]

**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**

 ```js
module.exports = {
    globals: {
        "ts-jest": {
            diagnostics: false,
            isolatedModules: true,
        },
    },
    moduleDirectories: ["<rootDir>/../../node_modules"],
    moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
    moduleNameMapper: {
        "\\.css$": "identity-obj-proxy",
        "\\.scss$": "identity-obj-proxy",
        "^@cling/(.*)$": "<rootDir>/../$1",
    },
    reporters: ["default"],
    setupFilesAfterEnv: ["<rootDir>/../lib.shared.test/jest_setup.ts"],
    snapshotSerializers: [],
    preset: "jest-playwright-preset",
    testMatch: ["<rootDir>/__tests__/**/*.spec.ts?(x)"],
    transform: {"^.+\\.tsx?$": "ts-jest"},
}
```

This is a sub-project in a monorepo. But even if I use `jest-playwright-preset` in the main configuration it won't work.

**Additional context**
All's working fine with Jest 26.6.3

**Comment by mmarkelov** [comment]
@flunderpero sorry for late response. I just don't have much time to look through new `Jest` version. I just tried to install some dependencies by myself and it helped.
```
// package.json
...
"dependencies": {
    "expect-playwright": "^0.3.2",
    "jest": "^27.0.0-next.7",
    "jest-playwright-preset": "1.5.1",
    "jest-runner": "^27.0.0-next.7",
    "playwright": "^1.10.0"
  }
```

**Comment by jakobrosenberg** [comment]
I just tried out `next.9`, but the below fix did unfortunately not help
```
        "expect-playwright": "^0.3.4",
        "jest": "^27.0.0-next.9",
        "jest-playwright-preset": "^1.5.2",
        "jest-runner": "^27.0.0-next.9",
        "playwright": "^1.10.0",
```

I posted the same issue on the Jest repo and got this from SimenB

> I'd assume it's an issue because they pull in v26 deps: https://github.com/playwright-community/jest-playwright/blob/f8ee23108bcac6801f073986a9bba56dfe461c2f/package.json#L48-L51
> Should probably be peer deps so users can plug in their own versions

https://github.com/facebook/jest/pull/11267#issuecomment-834101929

**Comment by mmarkelov** [comment]
@jakobrosenberg ok! Thanks for your comment, i'll move jest to peer dependencies

**Comment by thernstig** [comment]
I just updated to Jest 27 and ran into problems. I tracked it down to `jest-playwright-preset` and this update seems to have fixed it. I tested in `1.6.0-rc4`. See original issue on Jest: https://github.com/facebook/jest/issues/11440

I think this warrants to bump the major release of `jest-playwright-preset` as Jest 27 was just released. Otherwise more users upgrading will run into this problem of Jest not beeing a peer dependency in earlier releases.

**Comment by manzoorwanijk** [comment]
Still facing the same issue with:
```
"@testing-library/jest-dom": "^5.13.0",
"babel-jest": "^27.0.2",
"jest": "27.0.4",
"jest-circus": "27.0.4",
"jest-environment-jsdom": "27.0.3",
"jest-playwright-jsdom": "^0.0.4",
"jest-playwright-preset": "^1.6.1",
"jest-resolve": "27.0.4"
```

**Comment by lourd** [comment]
I just ran into this in my project that uses a monorepo. The root issue ended up being an indirect dependency on Jest v26 through `react-scripts`. No idea why! ¯\\_(ツ)_/¯  I resolved the issue by [specifying a resolution with yarn](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to the same one I was already depending on. E.g.:

```
...
"resolutions": {
  "react-scripts/jest": "27.2.3"
},
...
```
```Be sure to clear out your `node_modules` and reinstall after doing so!
